### ISSUE TITLE
Pytorch MNIST reference implementation - command line issue

### ISSUE THREAD

**Issue by juripapay** [Cerebras/modelzoo#2]
Please advise why the command line below fails. Thank you.

csrun_wse python-pt run.py -m train -p ./configs/params.yaml -cs 172.24.102.121

Launching: srun --unbuffered --kill-on-bad-exit --nodes=1 --tasks-per-node=8 --cpus-per-task=16 --gres=cs:1 singularity exec  /mnt/e1000/home/y26/shared/bin/cbcore-latest.sif python-pt run.py -m train -p ./configs/params.yaml -cs 172.24.102.121
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    run(MNISTModel, get_train_dataloader, get_eval_dataloader, set_defaults)
  File "../../../modelzoo/common/pytorch/run_utils.py", line 75, in run
    runner = PyTorchBaseRunner.create(model_fn, params)
  File "../../../modelzoo/common/pytorch/pytorch_base_runner.py", line 953, in create
    use_cbfloat16=use_cbfloat16,
  File "/cbcore/py_root/cerebras/framework/torch/utils/call_once.py", line 28, in wrapper
    output = f(*args, **kwargs)
  File "/cbcore/py_root/cerebras/framework/torch/core/configure.py", line 202, in initialize
    setattr(env, var, val)
  File "/cbcore/py_root/cerebras/framework/torch/core/cb_env_vars.py", line 643, in __setattr__
    raise AttributeError(f"Setting invalid attribute: {attr}")
AttributeError: Setting invalid attribute: appliance
srun: error: sdf-cs1: task 3: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=98165.0
slurmstepd: error: *** STEP 98165.0 ON sdf-cs1 CANCELLED AT 2022-12-20T20:16:23 ***
srun: error: sdf-cs1: tasks 1-2,4-5,7: Exited with exit code 1
srun: error: sdf-cs1: tasks 0,6: Exited with exit code 1

**Comment by juripapay** [comment]
The TensorFlow implementation of MNIST works perfectly well with the following command line:
 csrun_wse python run.py --mode train --cs_ip 172.24.102.121

**Comment by juripapay** [comment]
The reason for the error was the mismatch between ModelZoo versions 1.5 and 1.6.1.
